name: deploy-cocoapod-dry-run
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - test/dry-run
  pull_request:
    branches:
      - release/**
      - test/**
jobs:
  deploy-dry-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Install Cocoapods
        run: gem install cocoapods      
      
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: 11.7
      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
          LIB_VERSION: ${GITHUB_REF##*/}
        run: |
          set -eo pipefail
          export LIB_VERSION=0.12.1
          pod lib lint --allow-warnings --verbose
