name: deploy-cocoapod-dry-run
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - test/dry-run
  pull_request:
    branches:
      - release/**
      - test/**
jobs:
  deploy-dry-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Install Cocoapods
        run: gem install cocoapods      
      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          export LIB_VERSION=${GITHUB_REF:11}
          echo ${GITHUB_REF##*/}
          echo $LIB_VERSION
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
