name: publish pod
on:
  release:
    types: 
      - released
jobs:
  deploy:
    runs-on: macos-latest
    env:
      ARCHS_STANDARD: arm64 arm64e armv7 armv7s x86_64
      ARCHS: arm64 arm64e armv7 armv7s x86_64
    steps:
      - uses: actions/checkout@v2    
      - name: Install Cocoapods
        run: gem install cocoapods      
      
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: 11.7
      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
        run: |
          set -eo pipefail
          export LIB_VERSION=${GITHUB_REF:11}
          echo "LIB_VERSION ${LIB_VERSION}"
          pod lib lint --allow-warnings --verbose
          pod trunk push --allow-warnings
