name: Manage Pod Repo
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pod trunk register alex.syed@promethean.tv 'ptv-pod-master'
